#!/bin/bash

SRV=$PWD/srv

# MQTT Broker (mosquitto):
MQTT=$SRV/mqtt

docker run \
    --tty \
    --interactive \
    -p 1883:1883 \
    -p 9001:9001 \
    -v $MQTT/config:/mqtt/config:ro \
    -v $MQTT/log:/mqtt/log \
    -v $MQTT/data:/mqtt/data \
    rpi-mosquitto

