#!/bin/bash

SRV=$PWD/srv

# MQTT Broker (mosquitto):
MQTT=$SRV/mqtt

docker run \
    --tty \
    --interactive \
	--name mqtt-broker \
    --publish 1883:1883 \
    --publish 9001:9001 \
    --volume $MQTT/config:/mqtt/config:ro \
    --volume $MQTT/log:/mqtt/log \
    --volume $MQTT/data:/mqtt/data \
    rpi-mosquitto

