#!/bin/bash

. $(dirname $0)/common
INFLUXDB=$SRV/influxdb

docker run \
    --rm \
    --tty \
	--interactive \
	--name influxdb \
	--network $NETWORK \
	--publish 8086:8086 \
	--volume $INFLUXDB/influxdb.conf:/etc/influxdb/influxdb.conf \
	--volume $INFLUXDB/data:/var/lib/influxdb \
	tick-influxdb
